### ISSUE TITLE
Segmentation Fault when installing

### ISSUE THREAD

**Issue by globeone** [RMPR/atbswp#15]
When attempting to install on Ubuntu 18.04.4 LTS using the instructions it ends in a Segmentation Fault, with no further information as to what went wrong.

Python version
Python 3.6.9 64-bit

`sudo apt install git python3-dev python3-tk python3-setuptools python3-wheel python3-pip python3-wxgtk4.0`

`python3 -m pip install -r requirements-dev.txt`

`Installing collected packages: altgraph, attrs, chardet, urllib3, certifi, idna, requests, msgpack, CacheControl, cachy, pycparser, cffi, pastel, pylev, clikit, cleo, six, cryptography, webencodings, html5lib, more-itertools, zipp, importlib-metadata, jeepney, setuptools, pyrsistent, jsonschema, SecretStorage, keyring, lockfile, Pillow, python3-xlib, pyperclip, MouseInfo, numpy, ptyprocess, pexpect, pkginfo, shellingham, tomlkit, pyparsing, requests-toolbelt, poetry, PyMsgBox, PyScreeze, PyTweening, PyRect, PyGetWindow, PyAutoGUI, PyInstaller, python-xlib, pynput
Successfully installed CacheControl-0.12.5 MouseInfo-0.1.2 Pillow-6.2.2 PyAutoGUI-0.9.48 PyGetWindow-0.0.8 PyInstaller-3.6 PyMsgBox-1.0.7 PyRect-0.1.4 PyScreeze-0.1.25 PyTweening-1.0.3 SecretStorage-3.1.1 altgraph-0.16.1 attrs-19.3.0 cachy-0.3.0 certifi-2019.11.28 cffi-1.13.2 chardet-3.0.4 cleo-0.7.6 clikit-0.4.1 cryptography-2.8 html5lib-1.0.1 idna-2.8 importlib-metadata-0.23 jeepney-0.4.1 jsonschema-3.2.0 keyring-19.3.0 lockfile-0.12.2 more-itertools-8.0.2 msgpack-0.6.2 numpy-1.17.4 pastel-0.1.1 pexpect-4.7.0 pkginfo-1.5.0.1 poetry-1.0.0 ptyprocess-0.6.0 pycparser-2.19 pylev-1.3.0 pynput-1.6.0 pyparsing-2.4.5 pyperclip-1.7.0 pyrsistent-0.14.11 python-xlib-0.26 python3-xlib-0.15 requests-2.22.0 requests-toolbelt-0.8.0 setuptools-46.1.3 shellingham-1.3.1 six-1.14.0 tomlkit-0.5.8 urllib3-1.25.8 webencodings-0.5.1 zipp-0.6.0
Segmentation Fault (memorydump created)`

**Comment by globeone** [comment]
Might have found the issue
The version of zipp-0.6.0 doesn't exist.
`requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://pypi.org/simple/zipp-0-6-0/`

 I changed it to just get the package zipp (without a specific version) which gave me Successfully installed zipp-3.1.0

**Comment by RMPR** [comment]
You can submit a PR documenting the work around in the "Known Issues" section of the README

**Comment by globeone** [comment]
I did a pip3 upgrade which stopped the segmentation fault but is now showing other errors.
`pip3 install --upgrade pip`

PR has 177 different meanings as an acronym, I'm going to guess Problem Report? or do you mean a Push Request, or maybe a Promotion?

https://www.acronymfinder.com/PR.html
What does PR stand for?
Your abbreviation search returned 177 meanings

**Comment by globeone** [comment]
Here are the errors that the updated Python Installler Package (pip) is throwing.

`Error initializing plugin EntryPoint(name='Windows (alt)', value='keyrings.alt.Windows', group='keyring.backends').
Traceback (most recent call last):
  File "/home/kat/.local/lib/python3.6/site-packages/keyring/backend.py", line 203, in _load_plugins
    init_func = ep.load()
  File "/home/kat/.local/lib/python3.6/site-packages/importlib_metadata/__init__.py", line 95, in load
    module = import_module(match.group('module'))
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/lib/python3/dist-packages/keyrings/alt/Windows.py", line 9, in <module>
    from . import file_base
  File "/usr/lib/python3/dist-packages/keyrings/alt/file_base.py", line 13, in <module>
    from keyring.util.escape import escape as escape_for_ini
ModuleNotFoundError: No module named 'keyring.util.escape'
Error initializing plugin EntryPoint(name='file', value='keyrings.alt.file', group='keyring.backends').
Traceback (most recent call last):
  File "/home/kat/.local/lib/python3.6/site-packages/keyring/backend.py", line 203, in _load_plugins
    init_func = ep.load()
  File "/home/kat/.local/lib/python3.6/site-packages/importlib_metadata/__init__.py", line 95, in load
    module = import_module(match.group('module'))
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/lib/python3/dist-packages/keyrings/alt/file.py", line 11, in <module>
    from keyring.util.escape import escape as escape_for_ini
ModuleNotFoundError: No module named 'keyring.util.escape'
Error initializing plugin EntryPoint(name='pyfs', value='keyrings.alt.pyfs', group='keyring.backends').
Traceback (most recent call last):
  File "/home/kat/.local/lib/python3.6/site-packages/keyring/backend.py", line 203, in _load_plugins
    init_func = ep.load()
  File "/home/kat/.local/lib/python3.6/site-packages/importlib_metadata/__init__.py", line 95, in load
    module = import_module(match.group('module'))
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/lib/python3/dist-packages/keyrings/alt/pyfs.py", line 8, in <module>
    from keyring.util.escape import escape as escape_for_ini
ModuleNotFoundError: No module named 'keyring.util.escape'`

**Comment by globeone** [comment]
Here are the errors that the installer is throwing now.

`Error initializing plugin EntryPoint(name='Windows (alt)', value='keyrings.alt.Windows', group='keyring.backends').
Traceback (most recent call last):
  File "/home/$USER/.local/lib/python3.6/site-packages/keyring/backend.py", line 203, in _load_plugins
    init_func = ep.load()
  File "/home/$USER/.local/lib/python3.6/site-packages/importlib_metadata/__init__.py", line 95, in load
    module = import_module(match.group('module'))
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/lib/python3/dist-packages/keyrings/alt/Windows.py", line 9, in <module>
    from . import file_base
  File "/usr/lib/python3/dist-packages/keyrings/alt/file_base.py", line 13, in <module>
    from keyring.util.escape import escape as escape_for_ini
ModuleNotFoundError: No module named 'keyring.util.escape'
Error initializing plugin EntryPoint(name='file', value='keyrings.alt.file', group='keyring.backends').
Traceback (most recent call last):
  File "/home/$USER/.local/lib/python3.6/site-packages/keyring/backend.py", line 203, in _load_plugins
    init_func = ep.load()
  File "/home/$USER/.local/lib/python3.6/site-packages/importlib_metadata/__init__.py", line 95, in load
    module = import_module(match.group('module'))
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/lib/python3/dist-packages/keyrings/alt/file.py", line 11, in <module>
    from keyring.util.escape import escape as escape_for_ini
ModuleNotFoundError: No module named 'keyring.util.escape'
Error initializing plugin EntryPoint(name='pyfs', value='keyrings.alt.pyfs', group='keyring.backends').
Traceback (most recent call last):
  File "/home/$USER/.local/lib/python3.6/site-packages/keyring/backend.py", line 203, in _load_plugins
    init_func = ep.load()
  File "/home/$USER/.local/lib/python3.6/site-packages/importlib_metadata/__init__.py", line 95, in load
    module = import_module(match.group('module'))
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/lib/python3/dist-packages/keyrings/alt/pyfs.py", line 8, in <module>
    from keyring.util.escape import escape as escape_for_ini
ModuleNotFoundError: No module named 'keyring.util.escape'`

**Comment by RMPR** [comment]
> PR has 177 different meanings as an acronym, I'm going to guess Problem Report? or do you mean a Push Request, or maybe a Promotion? 

Pull request

**Comment by RMPR** [comment]
> Here are the errors that the installer is throwing now.

Are you trying to build with Pyinstaller?

**Comment by globeone** [comment]
re: Pull Request
I started this adventure by pulling the source into Visual Studio Code, first thing.

Then I am just following the instructions in the Readme.md 
Did I miss the part about Pyinstaller? :thinking: 

These are the current instructions:
Debian
shell
sudo apt install git python3-dev python3-tk python3-setuptools python3-wheel python3-pip python3-wxgtk4.0
git clone https://github.com/RMPR/atbswp.git && cd atbswp
pip3 install --upgrade pip  **## this needs to be added to the instructions**
python3 -m pip install -r requirements-dev.txt  **## here is where the instructions segfault**
python3 atbswp/atbswp.py

**Comment by globeone** [comment]
Hmmm the PIP dev's say that one shouldn't do a pip3 install --upgrade pip :unamused: 
https://github.com/pypa/pip/issues/5599

**Comment by globeone** [comment]
:facepalm: 
It may be that Ubuntu 18.04 doesn't have a high enough Python3 version.
I tried the poetry option and got the following error message. 

poetry build
The currently activated Python version 3.6.9 is not supported by the project (^3.7).
Trying to find and use a compatible version. 

[NoCompatiblePythonVersionFound]
Poetry was unable to find a compatible version. If you have one, you can explicitly use it via the "env use" command.

**Comment by RMPR** [comment]
> Did I miss the part about Pyinstaller? thinking
Nevermind.

> python3 -m pip install -r requirements-dev.txt ## here is where the instructions segfault
Better explanation.

> Hmmm the PIP dev's say that one shouldn't do a pip3 install --upgrade pip 
Never recommended you to do so.

> It may be that Ubuntu 18.04 doesn't have a high enough Python3 version.
Quite possibly but the project has been built on Ubuntu, so it's also surprising.

Can you reset your pip version to use the one provided by apt and retry? But this time instead of `python3 -m pip install -r requirements-dev.txt`, add the `user` argument: 
```
python3 -m pip install -r requirements-dev.txt --user
```

**Comment by globeone** [comment]
Earlier in the day I restored python3 back to default Ubuntu 18.04 and default pip3

I added the --user flag but unfortuntately it ends again in Segmentation Fault (memory dump created)
Segmentatiefout (geheugendump gemaakt)
Wonder if I can find the memory dump somewhere :thinking:

**Comment by RMPR** [comment]
I just released a standalone executable for Linux [here](https://github.com/RMPR/atbswp/releases/tag/v0.1) try it and don't hesitate to share your feedback.

**Comment by globeone** [comment]
I've just tested the standalone Linux executable in an Ubuntu 20.04 Live Image and it works really well. Each of the buttons does what are expected and recording and saving of the macros works well. Opening the Python file it's possible to change the speed and mouse movements. Saving to a pyc executable and reloading both also works.

Will try on an installed 20.04 virtual machine and an 18.04 bare metal machine

**Comment by globeone** [comment]
A quick Virus Total scan shows one false positive
https://www.virustotal.com/gui/file/cb2690d2edbac319d218d06eb7c856794d65de3866ba955c36e16ad22af94a00/detection

**Comment by globeone** [comment]
Just tested on bare metal Ubuntu 18.04. Everything except the hotkeys works. The slider changes the key but the keypress f9 doesn't stop start the recording and the keypress f10 doesn't start the playback. Moved the keypress to f11 still doesn't start the playback.

**Comment by RMPR** [comment]
> Everything except the hotkeys works. 

It's a very random bug, sometimes it works, sometimes no, it's more likely a problem with the GUI toolkit: wxPython, a simple workaround is to restart the program.
